version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - visitas-data:/data
    command: redis-server --appendonly yes

volumes:
  visitas-data:
